export const contact = {
  mobile: "06 10 04 08 90",
  mobileHref: "+33610040890",
  landline: "04 65 84 26 81",
  landlineHref: "+33465842681",
  email: "contact@phenix13.fr",
  address: "1120 route de Gémenos, 13400 Aubagne",
};

export const machines = [
  {
    slug: "mini-pelle-3-5-tonnes",
    title: "Mini-pelle 3,5 T",
    badge: "Le choix PHENIX",
    ownership: "Matériel PHENIX",
    price: "450 € HT / jour",
    transfer: "Transfert dès 160 € HT / trajet",
    size: "Largeur env. 1,70 à 1,80 m",
    use: "Chemins, plateformes, VRD, fouilles et chargement",
    image: "/images/studio-mini-pelle-35t.png",
    featured: true,
  },
  {
    slug: "mini-pelle-1-tonne",
    title: "Mini-pelle 800 kg / 1 T",
    badge: "Accès très étroits",
    ownership: "Mobilisable sur demande",
    price: "390 € HT / jour",
    transfer: "Transfert sur devis",
    size: "Passage env. 75 à 95 cm selon modèle",
    use: "Jardins, petits passages et tranchées compactes",
    image: "/images/studio-mini-pelle-1t.png",
  },
  {
    slug: "mini-pelle-1-5-tonne",
    title: "Mini-pelle 1,5 T",
    badge: "Format intermédiaire",
    ownership: "Mobilisable sur demande",
    price: "Tarif sur devis",
    transfer: "Transfert sur devis",
    size: "Largeur env. 1,00 à 1,10 m selon modèle",
    use: "Réseaux, jardins et terrassement résidentiel",
    image: "/images/studio-mini-pelle-15t.png",
  },
  {
    slug: "mini-chargeur",
    title: "Mini-chargeur",
    badge: "Chargement rapide",
    ownership: "Mobilisable sur demande",
    price: "330 € HT / jour",
    transfer: "Transfert sur devis",
    size: "Largeur env. 1,05 à 1,30 m",
    use: "Chargement, nivellement et déplacement de matériaux",
    image: "/images/studio-mini-chargeur.png",
  },
  {
    slug: "mini-dumper-1-5-tonne",
    title: "Mini-dumper 1,5 T",
    badge: "Évacuation compacte",
    ownership: "Mobilisable sur demande",
    price: "290 € HT / jour",
    transfer: "Transfert sur devis",
    size: "Gabarit selon modèle disponible",
    use: "Transport de terre et gravats dans les accès réduits",
    image: "/images/studio-mini-dumper.png",
  },
  {
    slug: "mini-pelle-8-tonnes",
    title: "Mini-pelle 8 T",
    badge: "Gros terrassement",
    ownership: "Mobilisable sur demande",
    price: "Tarif sur devis",
    transfer: "Transport exceptionnel sur devis",
    size: "Gabarit et accès à valider",
    use: "Gros volumes, plateformes et terrassement lourd",
    image: "/images/studio-mini-pelle-8t.png",
  },
  {
    slug: "chariot-telescopique",
    title: "Chariot télescopique",
    badge: "Levage & manutention",
    ownership: "Mobilisable sur demande",
    price: "Tarif sur devis",
    transfer: "Transport sur devis",
    size: "Hauteur et capacité selon modèle",
    use: "Palettes, matériaux et dépose en hauteur",
    image: "/images/studio-chariot-telescopique.png",
  },
];

export const recycledMaterials = [
  { name: "Terre de remblai végétale", grade: "Brute", price: "22 € / T", image: "/images/terre-remblai.jpg", use: "Remise à niveau" },
  { name: "Terre végétale tamisée", grade: "Tamisée", price: "26 € / T", image: "/images/terre-tamisee.jpg", use: "Gazon et plantations" },
  { name: "Terreaux végétaux broyés", grade: "Broyat", price: "70 € / m³", image: "/images/terreau.jpg", use: "Amélioration du sol" },
  { name: "Tout-venant recyclé", grade: "0/60", price: "24 € / T", image: "/images/tout-venant-recycle.jpg", use: "Chemins et fond de forme", featured: true },
  { name: "Sable à tranchée recyclé", grade: "0/6", price: "30 € / T", image: "/images/sable-recycle.jpg", use: "Protection des réseaux" },
  { name: "Gravier recyclé", grade: "6/10", price: "30 € / T", image: "/images/gravier-610-recycle.jpg", use: "Finition économique" },
  { name: "Gravier recyclé", grade: "10/20", price: "25 € / T", image: "/images/gravier-1020-recycle.jpg", use: "Drainage" },
  { name: "Ballast recyclé", grade: "30/60", price: "28 € / T", image: "/images/ballast-recycle.jpg", use: "Drainage fort" },
  { name: "Mélange à béton recyclé", grade: "Sable + gravier", price: "24 € / T", image: "/images/melange-beton-recycle.jpg", use: "Béton courant" },
];

export const nonRecycledMaterials = [
  ["Grave calcaire", "0/20", "45 € / T", "Fond de forme"],
  ["Gravier concassé", "6/10", "62 € / T", "Finition régulière"],
  ["Ballast", "20/40", "56 € / T", "Hérisson drainant"],
  ["Mélange à béton OGEO", "0/10", "53 € / T", "Béton courant"],
  ["Sable de carrière", "0/2C", "55 € / T", "Pose et réglage"],
  ["Sable Durance lavé", "0/4", "64 € / T", "Sable propre"],
  ["Sable St Anne enduit", "0/2", "111 € / T", "Finition fine"],
  ["Big Bag non réutilisable", "1,5 T", "25 € / U", "Selon disponibilité"],
];
