export const articles = [
  {
    slug: "refaire-chemin-acces-gravier-marseille",
    title: "Refaire un chemin d’accès en gravier autour de Marseille",
    description: "Les étapes pour rénover un chemin déformé : décaissement, drainage, tout-venant, compactage et gravier de finition.",
    category: "Chemins & accès",
    image: "/images/terrassement-chemin-premium.png",
    intro: "Un chemin qui se creuse, retient l’eau ou produit des ornières ne se répare pas durablement avec une simple couche de gravier. Le résultat dépend surtout de la préparation du fond et de l’évacuation de l’eau.",
    sections: [
      ["Pourquoi les trous reviennent-ils ?", "Les passages répétés, une couche trop fine, un sol meuble et l’absence de pente déplacent les matériaux. Ajouter du gravier sans corriger la base masque souvent le problème pendant quelques semaines seulement."],
      ["Les principales étapes", "On commence par contrôler l’accès des engins et les niveaux. Selon l’état du chemin, le terrain est décaissé ou simplement repris. Une pente régulière est créée, puis une couche de fond en tout-venant est mise en place et compactée. Le gravier de finition vient seulement après."],
      ["Quel matériau choisir ?", "Le tout-venant recyclé est souvent pertinent pour constituer une base économique. Un gravier non recyclé ou concassé peut être retenu en surface lorsqu’un aspect plus régulier est recherché. L’épaisseur dépend du sol, du passage de véhicules et de l’état existant."],
      ["Quand prévoir un drainage ?", "Si l’eau arrive d’un talus, stagne contre un mur ou traverse le chemin, une pente seule peut être insuffisante. Un fossé, un drain, une zone d’infiltration ou une reprise des écoulements doit alors être étudié avant la couche de finition."],
    ],
    checklist: ["Longueur et largeur du chemin", "Photos des ornières et écoulements", "Largeur du portail ou du passage", "Type de véhicules utilisés", "Finition souhaitée"],
  },
  {
    slug: "tranchee-reseau-portail-electrique",
    title: "Tranchée pour portail électrique et réseau enterré",
    description: "Comment préparer une tranchée, les gaines et les fondations avant la pose d’un portail à Marseille.",
    category: "VRD & portail",
    image: "/images/terrassement-vrd-premium.png",
    intro: "Un nouveau portail peut nécessiter plusieurs travaux en même temps : alimentation électrique, interphone, éclairage, évacuation d’eau et fondations. Les anticiper évite de rouvrir le terrain après la pose.",
    sections: [
      ["Ce qu’il faut définir avant de creuser", "Le poseur du portail ou l’électricien doit préciser l’emplacement du moteur, des cellules, du visiophone et des éventuels éclairages. Le type de portail, battant ou coulissant, influence aussi les fondations et les réservations."],
      ["Tranchée et gaines", "La largeur et la profondeur dépendent des réseaux, du terrain et des règles applicables. Les gaines doivent être adaptées à leur usage, protégées par un lit de sable et repérées. Les rayons de courbure doivent permettre le passage ultérieur des câbles."],
      ["Fondations et seuil", "Un portail coulissant demande généralement une longrine et une zone de refoulement correctement préparées. Pour un portail battant, les piliers et le seuil doivent reprendre les efforts. PHENIX STS peut préparer les fouilles et passages avant l’intervention des corps de métier concernés."],
      ["Coordonner les intervenants", "Le devis doit distinguer le terrassement, les fournitures, la maçonnerie, l’électricité et la pose du portail. Cette coordination protège le planning et évite les zones oubliées."],
    ],
    checklist: ["Plan ou devis du portail", "Emplacement du compteur", "Longueur de la tranchée", "Nature du sol", "Accès disponible pour la mini-pelle"],
  },
  {
    slug: "terrassement-apres-recherche-fuite",
    title: "Terrassement après localisation d’une fuite d’eau",
    description: "Dégager proprement une canalisation après la localisation d’une fuite, puis préparer la réparation et le remblaiement.",
    category: "Canalisation",
    image: "/images/terrassement-vrd-premium.png",
    intro: "Le terrassement intervient après la localisation de la fuite par le plombier, le gestionnaire du réseau ou un spécialiste. L’objectif est d’accéder à la canalisation sans ouvrir inutilement toute la propriété.",
    sections: [
      ["Localiser avant d’ouvrir", "Une indication précise réduit le volume de terre à déplacer et le risque de détériorer d’autres réseaux. Le marquage doit être visible et les plans disponibles doivent être transmis avant l’arrivée de l’engin."],
      ["Choisir la bonne machine", "Une mini-pelle compacte convient aux jardins et passages étroits. Une machine de 3,5 tonnes offre davantage de rendement et de stabilité lorsque l’accès le permet. À proximité immédiate du réseau, la finition peut nécessiter une excavation manuelle."],
      ["Préparer l’intervention du réparateur", "La fouille doit offrir un espace de travail suffisant, rester stable et permettre l’évacuation de l’eau. Le plombier peut alors remplacer la partie défectueuse et contrôler la réparation avant remblaiement."],
      ["Remblayer sans fragiliser le réseau", "La canalisation réparée est protégée avec un matériau adapté, puis les couches sont remises en place progressivement. Une finition provisoire peut être préférable avant de refaire un revêtement définitif."],
    ],
    checklist: ["Repérage précis de la fuite", "Plans des réseaux", "Photos de l’accès", "Profondeur estimée", "Coordonnées du réparateur"],
  },
  {
    slug: "tout-venant-recycle-utilisation-chemin",
    title: "Tout-venant recyclé : pour quels travaux l’utiliser ?",
    description: "Comprendre les usages du tout-venant recyclé pour les chemins, parkings, remblais et fonds de forme.",
    category: "Agrégats",
    image: "/images/tout-venant-recycle.jpg",
    intro: "Le tout-venant recyclé est un matériau économique souvent utilisé sous une finition. Il est particulièrement intéressant lorsqu’on recherche de la portance et du volume sans payer un matériau décoratif.",
    sections: [
      ["Une base, pas toujours une finition", "Sa granulométrie mélange différentes tailles de grains. Une fois réglé et compacté, il crée une couche stable pour un chemin, un parking ou une plateforme. Son aspect peut varier selon les lots."],
      ["Les usages adaptés", "Il convient aux fonds de forme, remblaiements, chemins d’accès, plateformes et certaines zones de circulation. Il peut aussi servir à remettre un terrain à niveau lorsque le projet prévoit une couche supérieure."],
      ["Quand choisir du non recyclé ?", "Pour une finition très régulière, une teinte contrôlée ou un usage soumis à une prescription technique précise, un matériau de carrière non recyclé peut être préférable."],
      ["Quantité et livraison", "La quantité dépend de la surface, de l’épaisseur après compactage et du foisonnement. Avec un petit camion, plusieurs rotations peuvent être nécessaires, mais l’accès résidentiel est souvent plus simple."],
    ],
    checklist: ["Surface en mètres carrés", "Épaisseur souhaitée", "Usage futur de la zone", "Accès du camion", "Possibilité de déchargement"],
  },
  {
    slug: "choisir-mini-pelle-acces-etroit",
    title: "Quelle mini-pelle choisir pour un accès étroit ?",
    description: "Comparer une mini-pelle de 1 t, 1,5 t et 3,5 t selon le passage, le rendement et les travaux.",
    category: "Location d’engins",
    image: "/images/catalogue-mini-pelle-1t.png",
    intro: "La plus petite machine n’est pas automatiquement la moins chère pour le chantier. Il faut trouver le meilleur compromis entre largeur de passage, stabilité, profondeur et rendement.",
    sections: [
      ["Mini-pelle 800 kg à 1 tonne", "Elle passe dans certains portails ou passages latéraux très réduits. Elle est adaptée aux petites tranchées et aux jardins, mais son rendement et sa stabilité sont inférieurs à ceux d’une machine plus lourde."],
      ["Mini-pelle 1,5 tonne", "Ce format intermédiaire conserve un gabarit compact tout en apportant plus de stabilité et de capacité. Il est intéressant pour les réseaux et terrassements résidentiels lorsque le passage le permet."],
      ["Mini-pelle 3,5 tonnes", "Elle devient le choix de référence pour les chemins, plateformes, fouilles et chargements. Son rendement réduit parfois le nombre de journées nécessaires, mais elle demande un accès plus large et un transport adapté."],
      ["Les mesures à envoyer", "Mesurez le point le plus étroit, pas seulement le portail. Contrôlez aussi la hauteur, les virages, les marches, les pentes, les dalles et la résistance du sol."],
    ],
    checklist: ["Largeur minimale réelle", "Hauteur disponible", "Virages ou marches", "Nature du travail", "Distance entre l’accès et la zone"],
  },
  {
    slug: "vrd-definition-travaux-maison",
    title: "Travaux VRD : à quoi cela correspond pour une maison ?",
    description: "Explication simple des travaux de voirie et réseaux divers pour l’eau, l’électricité, les évacuations et les accès.",
    category: "VRD",
    image: "/images/terrassement-vrd-premium.png",
    intro: "VRD signifie voirie et réseaux divers. Pour un particulier, cela regroupe surtout les travaux extérieurs permettant de desservir une maison, un portail, une extension ou une dépendance.",
    sections: [
      ["Quels réseaux sont concernés ?", "L’eau potable, l’électricité, les télécommunications, les eaux usées et parfois les eaux pluviales. Chaque réseau possède ses contraintes de profondeur, de protection, d’écartement et de signalisation."],
      ["Le rôle du terrassement", "Le terrassier ouvre les tranchées, prépare le fond, facilite la pose des gaines ou canalisations puis remblaie après contrôle. La coordination avec l’électricien, le plombier ou le gestionnaire du réseau est indispensable."],
      ["Voirie et accès", "Les VRD comprennent aussi la préparation des voies d’accès, parkings et plateformes nécessaires à l’utilisation de la propriété. Les pentes et l’écoulement de l’eau doivent être pensés avant la finition."],
      ["Pourquoi demander plusieurs informations ?", "La distance, la profondeur, la nature du terrain, les réseaux existants et l’accès des engins changent fortement le coût. Des photos, un plan et les prescriptions des intervenants permettent un devis plus fiable."],
    ],
    checklist: ["Plan de masse", "Prescriptions des concessionnaires", "Longueur des réseaux", "Profondeur demandée", "Accès engin et évacuation"],
  },
];
